export const SCENARIO_DESCRIPTIONS: Record<string, string> = {
  'SAP_COM_0227': '(Deprecated) Marketing - Campaign Execution - Twitter Integration',
  'SAP_COM_0346': '(Deprecated) Product Lifecycle Management - Product Structure Integration',
  'SAP_COM_0901': 'ABAP Test Cockpit - ATC Run Integration',
  'SAP_COM_0942': 'Advanced Backorder Processing Integration',
  'SAP_COM_0438': 'Advanced Compliance Reporting Integration using SLHACR',
  'SAP_COM_0A49': 'AI-Assisted Situation Handling Integration',
  'SAP_COM_0454': 'Application Monitoring Integration (Obsolete)',
  'SAP_COM_0508': 'Ariba Network - Buyer Integration via CIG Integration',
  'SAP_COM_0081': 'Ariba Network - Supplier Integration',
  'SAP_COM_0032': 'Ariba Network Integration',
  'SAP_COM_0244': 'Asset Central Foundation for Maintenance Execution Integration',
  'SAP_COM_0262': 'Asset Intelligence Network for Product Information Integration',
  'SAP_COM_0395': 'Asset Management Master Data Integration',
  'SAP_COM_0927': 'Assignment Status for Project Demands Integration',
  'SAP_COM_0790': 'Assortment Module Integration',
  'SAP_COM_0935': 'Available-to-Promise (ATP) Check Integration',
  'SAP_COM_0379': 'Bank - Bank Integration',
  'SAP_COM_0141': 'Batch Management - Batch IDoc/RFC Inbound Integration',
  'SAP_COM_0337': 'Batch Management - Batch OData Inbound Integration',
  'SAP_COM_0774': 'Batch Management - Batch SOAP Inbound Integration',
  'SAP_COM_0855': 'Batch Management - Batch SOAP Outbound Integration',
  'SAP_COM_0120': 'Billing Integration',
  'SAP_COM_0745': 'Block Intercompany Postings Integration',
  'SAP_COM_0349': 'Buffer Profile Integration',
  'SAP_COM_0359': 'Buffer Sizing Integration',
  'SAP_COM_0888': 'Business Data Orchestration - UI Integration',
  'SAP_COM_0594': 'Business Data Orchestration Integration',
  'SAP_COM_0121': 'Business Event Handling Integration (Obsolete)',
  'SAP_COM_0A54': 'Business Event Log - SQL Read Integration',
  'SAP_COM_0943': 'Business Object Cost Center Integration',
  'SAP_COM_0A91': 'Business Object Project Settlement Rules Integration',
  'SAP_COM_0091': 'Business Partner, Customer and Supplier Blocking Integration',
  'SAP_COM_0008': 'Business Partner, Customer and Supplier Integration',
  'SAP_COM_0394': 'Business Place Integration',
  'SAP_COM_0698': 'Business Process Intelligence Integration',
  'SAP_COM_0523': 'Business Process Monitoring Push Integration',
  'SAP_COM_0366': 'Business Role Change Document Integration',
  'SAP_COM_0A04': 'Business Role Read Integration',
  'SAP_COM_0345': 'Business Situation Integration',
  'SAP_COM_0376': 'Business Situation Master Data Integration',
  'SAP_COM_0706': 'Business Solution Order Integration',
  'SAP_COM_0327': 'Business User Change Document Integration',
  'SAP_COM_0889': 'Business User Logon Details Read Integration',
  'SAP_COM_0083': 'Central Finance Subsidiary Integration',
  'SAP_COM_0A94': 'Central Payment Repository - Requested Payment Integration',
  'SAP_COM_0A13': 'Certificate Read Integration',
  'SAP_COM_0160': 'Classification Systems Integration',
  'SAP_COM_0163': 'Classification Systems OData/SOAP Integration',
  'SAP_COM_0A31': 'Cloud Integration Automation Integration',
  'SAP_COM_0430': 'CMIS Repository Synchronization Integration',
  'SAP_COM_0054': 'Commercial Project Integration',
  'SAP_COM_0A07': 'Communication Arrangement Read Integration',
  'SAP_COM_0400': 'Communication Management - HTTP Inbound Test Integration',
  'SAP_COM_0401': 'Communication Management - HTTP Outbound Test Integration',
  'SAP_COM_0A48': 'Communication Management Integration',
  'YY1_GLACCOUNTLINEITEM': 'Communication Scenario for GLAccountLineItem',
  'YY1_GLACCOUNTLINEITEM_V2': 'Communication Scenario for GLACCOUNTLINEITEM_V2',
  'YY1_I_GLACCLINEITEM': 'Communication Scenarion for I_GLAccountLineItem',
  'SAP_COM_0A06': 'Communication System Read Integration',
  'SAP_COM_0A05': 'Communication User Read Integration',
  'SAP_COM_0946': 'Complaint Handling Integration',
  'SAP_COM_0070': 'Concur Integration',
  'SAP_COM_0536': 'Concur POC Integration',
  'SAP_COM_0A08': 'Content Security Policy Read Integration',
  'SAP_COM_0682': 'Contract Accounting - Payment Information Integration',
  'SAP_COM_0298': 'Contract Proposal Integration (Deprecated)',
  'SAP_COM_0165': 'Convergent Invoicing Integration',
  'SAP_COM_0158': 'Credit Memo Request Integration',
  'SAP_COM_0722': 'CSN Exposure Integration',
  'SAP_COM_0464': 'Custom Code Migration Integration',
  'SAP_COM_0449': 'Custom Services for Citizen Integration',
  'SAP_COM_0589': 'Customer Data Return Integration',
  'SAP_COM_0134': 'Customer Material Info Record Integration',
  'SAP_COM_0459': 'Customer Return Bulk Integration',
  'SAP_COM_0497': 'Customer Return Bulk Replication Integration',
  'SAP_COM_0157': 'Customer Return Integration',
  'SAP_COM_0730': 'Customer Type Integration',
  'SAP_COM_0080': 'Data Quality Management Integration',
  'SAP_COM_0209': 'Data Warehouse - ODP Data Extraction Integration',
  'SAP_COM_0159': 'Debit Memo Request Integration',
  'SAP_COM_0570': 'Delivery Insights Integration (Obsolete)',
  'SAP_COM_0571': 'Delivery Insights Replication App Integration (Obsolete)',
  'SAP_COM_0106': 'Delivery Processing Integration',
  'SAP_COM_0557': 'Digital Manufacturing for Network wth Quality Info Record Integration (Obsolete)',
  'SAP_COM_0693': 'Digital Vehicle Integration',
  'SAP_COM_0426': 'Direct Material Sourcing With Blockchain Integration',
  'SAP_COM_0077': 'Distributed Manufacturing Integration (Deprecated)',
  'SAP_COM_0854': 'Document and Reporting Compliance Cloud Edition Integration',
  'SAP_COM_0703': 'Document Compliance - Electronic Document File Integration',
  'SAP_COM_0626': 'Document Compliance Localization Extension Integration (Obsolete)',
  'SAP_COM_0529': 'Document Compliance PEPPOL Integration',
  'SAP_COM_0A82': 'Document Information Extraction Integration',
  'SAP_COM_0872': 'DRC - External reporting system integration',
  'SAP_COM_0548': 'E-Mail - Outbound Integration',
  'SAP_COM_0A52': 'EBPP Payment Request Integration',
  'SAP_COM_0448': 'eDocument - Argentina eInvoice Integration',
  'SAP_COM_0669': 'eDocument - Chile eInvoice and Delivery Note Integration',
  'SAP_COM_0670': 'eDocument - Colombia eInvoice and Incoming eInvoice Integration',
  'SAP_COM_0255': 'eDocument - eInvoice and ePayment for Mexico Integration',
  'SAP_COM_0689': 'eDocument - Greece electronic Tax register books Integration',
  'SAP_COM_0417': 'eDocument - Hungary Invoice Registration Integration',
  'SAP_COM_0629': 'eDocument - India eInvoice Solution Integration.',
  'SAP_COM_0429': 'eDocument - India eWay Bill Solution Integration',
  'SAP_COM_0418': 'eDocument - Italy eInvoice and Incoming eInvoice Integration',
  'SAP_COM_0873': 'eDocument - Peru eInvoice and Delivery Note Integration',
  'SAP_COM_0856': 'eDocument - Poland eInvoice Integration',
  'SAP_COM_0631': 'eDocument - Portugal eInvoice Integration',
  'SAP_COM_0494': 'eDocument - Portugal Transport Registration Integration',
  'SAP_COM_0859': 'eDocument - Romania eInvoice Integration',
  'SAP_COM_0898': 'eDocument - Saudi Arabia eInvoicing Integration',
  'SAP_COM_0A19': 'eDocument - Serbia eInvoice Integration',
  'SAP_COM_0877': 'eDocument - Slovakia eInvoice Integration',
  'SAP_COM_0468': 'eDocument - South Korea eInvoice Integration',
  'SAP_COM_0419': 'eDocument - Spain Invoice Registration Integration',
  'SAP_COM_0846': 'eDocument - Switzerland eInvoice and Incoming eInvoice Integration',
  'SAP_COM_0851': 'eDocument - Thailand eInvoice Integration',
  'SAP_COM_0421': 'eDocument - Turkey eDelivery Note and Incoming eDelivery Note Integration',
  'SAP_COM_0422': 'eDocument - Turkey eInvoice and Incoming eInvoice Integration',
  'SAP_COM_0225': 'eDocument - VAT Register Books for Spain Integration',
  'SAP_COM_0688': 'EHS - Authority Servers with E-Waste Documents Integration',
  'SAP_COM_0857': 'Electronic Document - Egypt Electronic Invoice Integration',
  'SAP_COM_0056': 'Employee Central Cost Center Integration',
  'SAP_COM_0441': 'Employee Central Financial Master Data Integration',
  'SAP_COM_0028': 'Employee Central Payroll Integration',
  'SAP_COM_0535': 'Employee Central via SAP CPI Integration',
  'SAP_COM_0001': 'Employee Integration',
  'SAP_COM_0518': 'Enterprise Contract Management - DocuSign Integration',
  'SAP_COM_0521': 'Enterprise Contract Management - External Linked Objects Integration',
  'SAP_COM_0809': 'Enterprise Contract Management - Hub System Integration',
  'SAP_COM_0868': 'Enterprise Contract Management - Icertis Integration',
  'SAP_COM_0869': 'Enterprise Contract Management - Icertis Operational Integration',
  'SAP_COM_0890': 'Enterprise Contract Management - Icertis UI Integration',
  'SAP_COM_0823': 'Enterprise Contract Management - Microsoft Teams Integration',
  'SAP_COM_0824': 'Enterprise Contract Management - Microsoft Teams Operational Integration',
  'SAP_COM_0437': 'Enterprise Contract Management and Assembly Integration',
  'SAP_COM_0A23': 'Enterprise Event Enablement - Direct Event Inbound Integration',
  'SAP_COM_0A22': 'Enterprise Event Enablement - Direct Event Outbound Integration',
  'SAP_COM_0092': 'Enterprise Eventing Integration',
  'SAP_COM_0963': 'Enterprise Project - Blockable Function Integration',
  'SAP_COM_0470': 'Enterprise Project - Central Finance Integration',
  'SAP_COM_0250': 'Enterprise Project - Collaboration Integration',
  'SAP_COM_0252': 'Enterprise Project - Collaboration UI Integration',
  'SAP_COM_0656': 'Enterprise Project - Collaborative Project Integration',
  'SAP_COM_0723': 'Enterprise Project - Internal Project Type Integration',
  'SAP_COM_0726': 'Enterprise Project - Project Priority Integration',
  'SAP_COM_0725': 'Enterprise Project - Project Processing Status Integration',
  'SAP_COM_0724': 'Enterprise Project - Project Profile Integration',
  'SAP_COM_0917': 'Enterprise Project Element - Deliverable Type Integration',
  'SAP_COM_0308': 'Enterprise Project Integration',
  'SAP_COM_0945': 'Enterprise Project Service Organization Integration',
  'SAP_COM_0369': 'Environment, Health and Safety - Incident Reporting Integration',
  'SAP_COM_0671': "Environment, Health and Safety - Workers' Compensation Associations Integration",
  'SAP_COM_0747': 'Environment, Health, and Safety - Automatic Data Collection Integration',
  'SAP_COM_0A71': 'Environment, Health, and Safety - SAP SuccessFactors Learning Integration',
  'SAP_COM_0602': 'Event Consumption Model Inbound Test Integration',
  'SAP_COM_0634': 'Excise Tax EMCS Integration',
  'SAP_COM_0568': 'Excise Tax Integration',
  'SAP_COM_0694': 'Extensibility UI Text Translation Adaptation Integration',
  'SAP_COM_0176': 'External Billing Document Request Integration',
  'SAP_COM_0301': 'External HR Workforce Integration',
  'SAP_COM_0177': 'External Sales and Use Tax Calculation Integration',
  'SAP_COM_0326': 'External Scheduler - Application Job Administration Integration',
  'SAP_COM_0064': 'External Scheduler - Application Job Scheduling Integration (Deprecated)',
  'SAP_COM_0944': 'Factory Calendar - Pull Inbound Integration',
  'SAP_COM_0732': 'Field Logistics - Manage Supplier Item Integration',
  'SAP_COM_0752': 'Field Logistics - Pack Container Integration',
  'SAP_COM_0753': 'Field Logistics - Shipment Voyage Integration',
  'SAP_COM_0952': 'Field Logistics Shipment Container Integration',
  'SAP_COM_0679': 'Field Logistics Supplier Item to Fieldglass Integration',
  'SAP_COM_0074': 'Fieldglass Integration',
  'SAP_COM_0321': 'Finance - Account Payable Configuration Integration',
  'SAP_COM_0313': 'Finance - Account Payable Payment Advice Integration',
  'SAP_COM_0251': 'Finance - Account Payable Positive Pay Integration',
  'SAP_COM_0316': 'Finance - Account Receivable Bank Statement Integration',
  'SAP_COM_0314': 'Finance - Account Receivable Payment Advice Integration',
  'SAP_COM_0303': 'Finance - Accounting Analytics Integration',
  'SAP_COM_0338': 'Finance - Accounting Correspondence Integration',
  'SAP_COM_0277': 'Finance - Accounting Document Integration',
  'SAP_COM_0179': 'Finance - Accounting Master Data Integration',
  'SAP_COM_0590': 'Finance - Accounts Payable Discount Management Integration',
  'SAP_COM_0759': 'Finance - Accounts Receivable Lockbox Integration',
  'SAP_COM_0719': 'Finance - Accounts Receivable SEPA Mandate Integration',
  'SAP_COM_0775': 'Finance - ACR Services for Partner Enablement Integration',
  'SAP_COM_0129': 'Finance - Activity Type Integration',
  'SAP_COM_0649': 'Finance - Advanced Payment Management - Watch List Screening Hits Integration',
  'SAP_COM_0648': 'Finance - Advanced Payment Management - Watch List Screening Integration',
  'SAP_COM_0315': 'Finance - Allocation Posting Integration',
  'SAP_COM_0278': 'Finance - Bank Account Inbound Integration',
  'SAP_COM_0279': 'Finance - Bank Account Outbound Integration',
  'SAP_COM_0256': 'Finance - Bank Connectivity Integration',
  'SAP_COM_0127': 'Finance - Bank Integration',
  'SAP_COM_0388': 'Finance - Bank Reconciliation Integration',
  'SAP_COM_0733': 'Finance - Brazilian ACR Reports Integration',
  'SAP_COM_0284': 'Finance - Cash Management Inbound Integration',
  'SAP_COM_0285': 'Finance - Cash Management Outbound Integration',
  'SAP_COM_0126': 'Finance - Central Entity Integration',
  'SAP_COM_0674': 'Finance - Central Finance SEPA Mandates Integration (Obsolete)',
  'SAP_COM_0727': 'Finance - China Payment Requisition Integration',
  'SAP_COM_0241': 'Finance - Cloud Consolidation Data Collection Integration',
  'SAP_COM_0336': 'Finance - Cloud Consolidation Master Data for Group Reporting Integration',
  'SAP_COM_0903': 'Finance - Cloud Consolidation Task for Group Reporting Integration',
  'SAP_COM_0348': 'Finance - Cloud Consolidation Transaction Data for Group Reporting Integration',
  'SAP_COM_0A83': 'Finance - Collections and Dispute Automation - Dispute Integration',
  'SAP_COM_0639': 'Finance - Contract Accounting Collection Agency Integration',
  'SAP_COM_0638': 'Finance - Contract Accounting External Cash Desk Integration',
  'SAP_COM_0663': 'Finance - Contract Accounting Factoring Integration',
  'SAP_COM_0696': 'Finance - Contract Accounting General Ledger Hub Integration',
  'SAP_COM_0731': 'Finance - Contract Accounting Integration',
  'SAP_COM_0511': 'Finance - Contract Accounting Integration for SAP Cash Application',
  'SAP_COM_0167': 'Finance - Contract Accounting Master Data Integration',
  'SAP_COM_0361': 'Finance - Contract Accounting Open Item Management Integration',
  'SAP_COM_0716': 'Finance - Contract Accounting Promise to Pay Integration',
  'SAP_COM_0380': 'Finance - Contract Accounting Security Deposits Integration',
  'SAP_COM_0458': 'Finance - Contract Accounting SEPA Mandate Integration',
  'SAP_COM_0579': 'Finance - Contract Accounting: Disconnection and Reconnection of Services',
  'SAP_COM_0357': 'Finance - Cost Center Activity Type Integration',
  'SAP_COM_0133': 'Finance - Cost Center Integration',
  'SAP_COM_0173': 'Finance - Credit Management Integration',
  'SAP_COM_0740': 'Finance - Credit Management Master Data Integration',
  'SAP_COM_0B18': 'Finance - Currency Exchange Rates Integration',
  'SAP_COM_0B17': 'Finance - Direct Debit Mandate Integration',
  'SAP_COM_0705': 'Finance - EBRR Manual Accruals Integration',
  'SAP_COM_0645': 'Finance - ELSTER Integration',
  'SAP_COM_0543': 'Finance - EU VAT Registration Number Validation Integration',
  'SAP_COM_0312': 'Finance - Event-Based Revenue Recognition Integration',
  'SAP_COM_0563': 'Finance - Fixed Asset Integration',
  'SAP_COM_0A93': 'Finance - Fixed Asset Master Data Integration',
  'SAP_COM_0A95': 'Finance - Fixed Asset Posting Integration',
  'SAP_COM_0A97': 'Finance - Fixed Asset Revaluation Index Integration',
  'SAP_COM_0A96': 'Finance - Fixed Asset Usage Object for UoP Depreciation Integration',
  'SAP_COM_0362': 'Finance - Freeze Period Integration',
  'SAP_COM_0370': 'Finance - Group Reporting Planning Integration',
  'SAP_COM_0248': 'Finance - Group Reporting Reported Financial Data Integration',
  'SAP_COM_0377': 'Finance - Intercompany Matching Item Integration',
  'SAP_COM_0125': 'Finance - Internal Order Integration',
  'SAP_COM_0559': 'Finance - Master Data Integration for Cost Center Integration (Obsolete)',
  'SAP_COM_0585': 'Finance - Master Data Service for Account Assignment Elements Integration',
  'SAP_COM_0A62': 'Finance - Memo Records 2.0 Integration',
  'SAP_COM_0654': 'Finance - One Time Password Integration',
  'SAP_COM_0331': 'Finance - Payment Advice Integration',
  'SAP_COM_0711': 'Finance - Payment Approval Integration',
  'SAP_COM_0132': 'Finance - Payment Request Integration',
  'SAP_COM_0002': 'Finance - Posting Integration',
  'SAP_COM_0131': 'Finance - Profit Center Integration',
  'SAP_COM_0368': 'Finance - Profit Center OData Integration',
  'SAP_COM_0754': 'Finance - Reassign Costs and Revenues Integration',
  'SAP_COM_0852': 'Finance - SAP SuccessFactors Payroll - Journal Entry Integration',
  'SAP_COM_0844': 'Finance - Slovakia Bank Accounts Register Integration',
  'SAP_COM_0130': 'Finance - Statistical Key Figure Integration',
  'SAP_COM_0B07': 'Finance - Statistical Key Figure OData Integration',
  'SAP_COM_0554': "Finance - Third-party's Communication Client Integration",
  'SAP_COM_0794': 'Finance - Transaction Data - Write - for Group Reporting Integration',
  'SAP_COM_0923': 'Finance - Treasury Financial Transaction NPV Integration',
  'SAP_COM_0A85': 'Finance - Treasury FX Exposure Management Integration',
  'SAP_COM_0442': 'Finance - Treasury Payment Request Integration',
  'SAP_COM_0332': 'Finance - Treasury Position Flow Integration',
  'SAP_COM_0333': 'Finance - Treasury Posting Journal Integration',
  'SAP_COM_0853': 'Finance \u2013 SAP SuccessFactors Payroll \u2013 UI Integration',
  'SAP_COM_0580': 'Finance Employee Central Account Assignment Derivation Validation Integration',
  'SAP_COM_0B00': 'Finance-Contract Accounting Accounts Receivable/Accounts Payable Integration',
  'SAP_COM_0416': 'Financial Closing Integration',
  'SAP_COM_0566': 'Financial Tasklist Integration',
  'SAP_COM_0096': 'Financials - SAP Customer Engagement Center Integration',
  'SAP_COM_0114': 'Foundation Master Data Integration',
  'SAP_COM_0782': 'Goods Receipt Confirmation Integration',
  'SAP_COM_0230': 'GRC - Process Control and Risk Management Integration',
  'SAP_COM_0734': 'GRC - SAP Risk and Assurance Management Integration',
  'SAP_COM_0391': 'GRC SAP Privacy Governance Integration',
  'SAP_COM_0364': 'Handling Unit Integration',
  'SAP_COM_0932': 'IC Configure - Variant Configuration Bundle Model Integration',
  'SAP_COM_0093': 'Identity Management Integration',
  'SAP_COM_0193': 'Identity Provisioning Integration',
  'SAP_COM_0431': 'Image Based Ordering for S/4H Procurement ML Integration (Deprecated)',
  'SAP_COM_0A42': 'Incident Management - OSHA Reporting Integration',
  'SAP_COM_0546': 'Incoming China VAT Invoice Integration',
  'SAP_COM_0110': 'Inspection Master Data Integration',
  'SAP_COM_0810': 'Integration of Enterprise Contract Management - Connected System',
  'SAP_COM_0446': 'Intelligent Accruals Recommendation Integration',
  'SAP_COM_0718': 'Intelligent Product Proposal Integration',
  'SAP_COM_0572': 'Intelligent Product Selection Consumption Integration',
  'SAP_COM_0538': 'Intelligent Product Selection Integration',
  'SAP_COM_0280': 'International Trade Content - Commodity Codes Integration',
  'SAP_COM_0281': 'International Trade Content - Control Classes Integration',
  'SAP_COM_0282': 'International Trade Content - Customs Tariff Numbers Integration',
  'SAP_COM_0240': 'Invoice Process Integration',
  'SAP_COM_0B08': 'Invoice Summary Output Integration',
  'SAP_COM_1238': 'Invoice Summary Output Integration (Deprecated)',
  'SAP_COM_0383': 'Joint Venture Accounting API Integration',
  'SAP_COM_0381': 'Joint Venture Partner Billing Files Integration',
  'SAP_COM_0882': 'Joule Integration',
  'SAP_COM_0330': 'Kanban Control Cycle Integration',
  'SAP_COM_0520': 'Kanban Summarized JIT Call Outbound Integration',
  'SAP_COM_0540': 'Key Mapping Client Integration',
  'SAP_COM_0539': 'Key Mapping Hub Integration',
  'SAP_COM_0647': 'Launchpad Content Exposure to SAP BTP Integration',
  'SAP_COM_0791': 'Legal Context Integration',
  'SAP_COM_0178': 'Legal Document Integration',
  'SAP_COM_0140': 'Legal Transaction Integration',
  'SAP_COM_0396': 'Maintenance Planning Integration',
  'SAP_COM_0397': 'Maintenance Processing Integration',
  'SAP_COM_0B27': 'Manage External Tax Items Integration',
  'SAP_COM_0765': 'Manage User-Defined Criteria Integration',
  'SAP_COM_0667': 'Manufacturing - MRP Change Request Integration',
  'SAP_COM_0522': 'Manufacturing Execution - Order and Confirmation Integration',
  'SAP_COM_0156': 'Manufacturing Execution Integration',
  'SAP_COM_0135': 'Marketing - Campaigns Integration (Obsolete)',
  'SAP_COM_0371': 'Marketing - Event Inbound Integration',
  'SAP_COM_1095': 'Marketing - Kubernetes Dialog Scaler Integration',
  'SAP_COM_0022': 'Marketing - Reporting Integration',
  'SAP_COM_0780': 'Master Data - Location Substitution Integration',
  'SAP_COM_0708': 'Master Data - Product Exclusion Integration',
  'SAP_COM_0779': 'Master Data - Product Substitution Control Integration',
  'SAP_COM_0778': 'Master Data - Product Substitution Group Integration',
  'SAP_COM_0707': 'Master Data - Product Substitution Integration',
  'SAP_COM_0581': 'Master Data Service for Proj Control Object Integate (Deprecated)| (Obsolete)',
  'SAP_COM_0108': 'Material Document Integration',
  'SAP_COM_0263': 'Material Document Outbound Notification Integration',
  'SAP_COM_0147': 'Material Price Changes and Inventory Values Integration',
  'SAP_COM_0164': 'Material Stock Integration',
  'SAP_COM_0447': 'Material Stock Quantity Replication Integration',
  'SAP_COM_0A79': 'MDG - Cloud Integration - Business Partner Pull Integration',
  'SAP_COM_0477': 'Message Monitoring - Error Propagation Integration',
  'SAP_COM_0569': 'Message Monitoring - Outbound Integration of Error Propagation',
  'SAP_COM_0578': 'Message Monitoring - SAP Alert Notification service for SAP BTP - Integration',
  'SAP_COM_0947': 'Migration Cockpit API Integration',
  'SAP_COM_0816': 'Migration Cockpit Direct Transfer Integration',
  'SAP_COM_0259': 'Migration Cockpit Integration',
  'SAP_COM_0678': 'Migration Cockpit Integration',
  'SAP_COM_0181': 'OData Metadata Integration',
  'SAP_COM_0B06': 'Omnichannel Promotion Pricing Services Integration',
  'SAP_COM_0046': 'Open Catalog Integration',
  'SAP_COM_0007': 'OpenText Business Event Integration',
  'SAP_COM_0577': 'Outgoing China VAT Invoice Integration',
  'SAP_COM_0881': 'Output Management - Output Queue Integration',
  'SAP_COM_0399': 'Packing Instruction Integration',
  'SAP_COM_0896': 'Packing Instruction Replication with Ariba Network Integration',
  'SAP_COM_0A38': 'Payables and Receivables Financing with Taulia',
  'SAP_COM_0644': 'Photo Replication for Workforce Integration',
  'SAP_COM_0107': 'Physical Inventory Document Integration',
  'SAP_COM_0A15': 'Planon Real Estate Management for SAP UI Integration',
  'SAP_COM_0398': 'Plant Maintenance Execution Integration',
  'SAP_COM_0319': 'Plant Maintenance Master Data Integration',
  'SAP_COM_0322': 'Plant Maintenance Notification Integration',
  'SAP_COM_0344': 'Plant Maintenance Order Integration',
  'SAP_COM_0814': 'Portugal Series Validation Code Registration Integration',
  'SAP_COM_0257': 'Portuguese Tax Authority Integration',
  'SAP_COM_0920': 'PRA Accounting Data Integration',
  'SAP_COM_0815': 'PRA Funds Notification Integration',
  'SAP_COM_0919': 'PRA Production Data Integration',
  'SAP_COM_0921': 'PRA Valuation Data Integration',
  'SAP_COM_0940': 'PRA Well Completion Daily Pressure Integration',
  'SAP_COM_0939': 'PRA Well Completion Downtime Integration',
  'SAP_COM_0938': 'PRA WellTest Integration',
  'SAP_COM_0806': 'PRA XI Inbound Integration',
  'SAP_COM_0373': 'Predictive Journal Entry Data Integration',
  'SAP_COM_0739': 'Predictive MRP Masterdata Integration',
  'SAP_COM_0911': 'Preferred Supplier List Integration (Deprecated)',
  'SAP_COM_0953': 'Preliminary Billing Document Integration',
  'SAP_COM_0861': 'Price Calculation - UI Integration',
  'SAP_COM_0294': 'Pricing Data Integration',
  'SAP_COM_0295': 'Pricing Data Replication Integration',
  'SAP_COM_0467': 'Printing - Notification Integration',
  'SAP_COM_0A86': 'Printing - Print Queue Administration Integration',
  'SAP_COM_0466': 'Printing - Pull Integration',
  'SAP_COM_0524': 'Procurement - Ariba Contract Management Integration',
  'SAP_COM_0450': 'Procurement - Ariba Sourcing Integration',
  'SAP_COM_0451': 'Procurement - External Sourcing Integration',
  'SAP_COM_0324': 'Procurement - Operational Supplier Evaluation Score Integration',
  'SAP_COM_0760': 'Procurement - Supplier Quotation Management Integration (Deprecated)',
  'SAP_COM_0526': 'Procurement \u2013 Ariba Supplier Risk Integration',
  'SAP_COM_0633': 'Procurement Central Sourcing - Ariba Sourcing Integration',
  'SAP_COM_0116': 'Procurement Master Data Integration',
  'SAP_COM_0152': 'Product Allocation Object Integration',
  'SAP_COM_0161': 'Product Allocation Sequence Integration',
  'SAP_COM_0792': 'Product Assignment to Distribution Center Integration',
  'SAP_COM_0115': 'Product Availability Information Integration',
  'SAP_COM_0309': 'Product Classification Integration',
  'SAP_COM_0797': 'Product Compliance - Integration',
  'SAP_COM_0666': 'Product Compliance - Integration of Third-Party Regulatory Content',
  'SAP_COM_0772': 'Product Compliance - Label Template Authoring Integration',
  'SAP_COM_0A60': 'Product Compliance - Logistics Inbound Integration',
  'SAP_COM_0786': 'Product Compliance - Regulatory Documentation Reference Service Integration',
  'SAP_COM_0514': 'Product Compliance - Regulatory Documentation Service Integration',
  'SAP_COM_0748': 'Product Compliance - Substance Volume Tracking Integration',
  'SAP_COM_0009': 'Product Integration',
  'SAP_COM_0339': 'Product Lifecycle Management - Change Record Integration',
  'SAP_COM_0150': 'Product Lifecycle Management - Core Master Data Integration',
  'SAP_COM_0151': 'Product Lifecycle Management - Engineering Change Management IDOC Integration',
  'SAP_COM_0937': 'Product Lifecycle Management - EPD Integration',
  'SAP_COM_0290': 'Product Lifecycle Management - Intelligent Product Design BOM Integration',
  'SAP_COM_0214': 'Product Lifecycle Management - Intelligent Product Design DMS Integration',
  'SAP_COM_0215': 'Product Lifecycle Management - Intelligent Product Design EADesigner Integration',
  'SAP_COM_0291': 'Product Lifecycle Management - Intelligent Product Design RD Integration',
  'SAP_COM_0428': 'Product Lifecycle Management - IPD Collaboration Change Record Integration',
  'SAP_COM_0105': 'Product Lifecycle Management - Master Data Integration',
  'SAP_COM_0254': 'Product Lifecycle Management - ML for Document Classification Integration',
  'SAP_COM_0866': 'Product Lifecycle Management - PLM System Inbound Integration',
  'SAP_COM_0867': 'Product Lifecycle Management - PLM System Outbound Integration',
  'SAP_COM_0136': 'Product Lifecycle Management - Recipe Development Integration',
  'SAP_COM_0A47': 'Product Lifecycle Management - UI Integration',
  'SAP_COM_0149': 'Product Lifecycle Management - Variant Configuration Integration',
  'SAP_COM_0751': 'Product Lifecycle Management - Variant Configuration Integration',
  'SAP_COM_0910': 'Product Sourcing Integration (Deprecated)',
  'SAP_COM_0104': 'Production Planning Integration',
  'SAP_COM_0519': 'Production Planning Master Data Integration',
  'SAP_COM_0328': 'Production Supply Area Integration',
  'SAP_COM_0704': 'Production Volume Management Integration (Deprecated)',
  'SAP_COM_0909': 'Project Billing Integration',
  'SAP_COM_0111': 'Project Control Integration',
  'SAP_COM_0925': 'Project Demand Category and Type Integration',
  'SAP_COM_0783': 'Project Demand Integration',
  'SAP_COM_0926': 'Project Demand Status Integration',
  'SAP_COM_0843': 'Project Management in SAP Project and Resource Management - UI Integration',
  'SAP_COM_0A09': 'Protection Allowlists Read Integration',
  'SAP_COM_0761': 'Public Sector API Integration',
  'SAP_COM_0101': 'Purchase Contract Integration',
  'SAP_COM_0A29': 'Purchase Order Accruals Review Integration',
  'SAP_COM_0053': 'Purchase Order Integration',
  'SAP_COM_0238': 'Purchase Order Process Integration',
  'SAP_COM_0113': 'Purchase Request for Quotation Integration',
  'SAP_COM_0102': 'Purchase Requisition Integration',
  'SAP_COM_0239': 'Purchase Requisition Process Integration',
  'SAP_COM_0103': 'Purchase Scheduling Agreement Integration',
  'SAP_COM_0123': 'Purchasing Category Integration',
  'SAP_COM_0145': 'Purchasing Info Record Integration',
  'SAP_COM_0166': 'Purchasing Quota Arrangement Integration',
  'SAP_COM_0162': 'Purchasing Source Integration',
  'SAP_COM_0588': 'Quality Certificate Exchange Integration',
  'SAP_COM_0389': 'Quality Certificate Inbound Integration',
  'SAP_COM_0358': 'Quality Info Record Integration',
  'SAP_COM_0124': 'Quality Inspection Process (with BAPI) Integration',
  'SAP_COM_0318': 'Quality Inspection Process Integration',
  'SAP_COM_0153': 'Quality Notification and Defect Processing Integration',
  'SAP_COM_0915': 'Read Access Log Integration',
  'YY1_READWORKFORCEPERSON': 'Read workforce person',
  'SAP_COM_0402': 'Remote Function Call - RFC Inbound Test Integration',
  'SAP_COM_0636': 'Remote Function Call - RFC Metadata Integration',
  'SAP_COM_0403': 'Remote Function Call - RFC Outbound Test Integration',
  'SAP_COM_0404': 'Remote Function Call - WebSocket RFC Inbound Test Integration',
  'SAP_COM_0405': 'Remote Function Call - Websocket RFC Outbound Test Integration',
  'SAP_COM_0902': 'Renegotiation Integration',
  'SAP_COM_0112': 'Reservation Integration',
  'SAP_COM_0928': 'Resource Assignment Source for Project Demands Integration',
  'SAP_COM_0A11': 'Resource Management in SAP Project and Resource Management - API Integration',
  'SAP_COM_0840': 'Resource Management in SAP Project and Resource Management - UI Integration',
  'SAP_COM_0560': 'Responsibility Management Team Integration',
  'SAP_COM_0640': 'Retail Merchandise Management - Point of sale Master data Integration',
  'SAP_COM_0652': 'Retail Merchandise Management - Point Of Sale Transaction Data Integration',
  'SAP_COM_0795': 'Returns Inspection OData v4 Integration',
  'SAP_COM_0701': 'Revenue Accounting Integration',
  'YY1_RM_SCENARIO': 'RM api call',
  'SAP_COM_0A33': 'S/4H Document and Reporting Compliance - SAP CIM Integration',
  'SAP_COM_0228': 'S/4HANA Activate New Features - Innovation Discovery System Integration',
  'SAP_COM_0837': 'S/4HANA QM/NCM - Quality Issue Resolution Integration',
  'SAP_COM_0641': 'Sales - Document Information Extraction Service Integration',
  'SAP_COM_0427': 'Sales Area Replication Integration',
  'SAP_COM_0A10': 'Sales Contract Bulk Replication Integration',
  'SAP_COM_0119': 'Sales Contract Integration',
  'SAP_COM_0325': 'Sales Credit Management Integration',
  'SAP_COM_0829': 'Sales Credit Management Outbound Integration',
  'SAP_COM_0117': 'Sales Inquiry Integration',
  'SAP_COM_0746': 'Sales Master Data Integration',
  'SAP_COM_0B03': 'Sales Material Determination Record Integration',
  'SAP_COM_0288': 'Sales Order Bulk Integration',
  'SAP_COM_0287': 'Sales Order Bulk Replication Integration',
  'SAP_COM_0109': 'Sales Order Integration',
  'SAP_COM_0334': 'Sales Order Without Charge Integration',
  'SAP_COM_0702': 'Sales Price Integration',
  'SAP_COM_0A12': 'Sales Quotation Bulk Replication Integration',
  'SAP_COM_0118': 'Sales Quotation Integration',
  'SAP_COM_0382': 'Sales Scheduling Agreements Consignment Issue Integration',
  'SAP_COM_0360': 'Sales Scheduling Agreements Integration',
  'SAP_COM_0444': 'Sales Scheduling Agreements With Buyers Integration',
  'SAP_COM_0223': 'Sales with Buyers Integration',
  'SAP_COM_0848': 'Sales with SAP Business Network Integration',
  'SAP_COM_0A69': 'SAP AI Core - GenAI - Customer Outbound Integration',
  'SAP_COM_0443': 'SAP Analytics Cloud for Liquidity Planning Integration',
  'SAP_COM_0087': 'SAP Analytics Cloud for Planning Integration',
  'SAP_COM_0065': 'SAP Analytics Cloud Integration',
  'SAP_COM_0545': 'SAP Ariba Buying Integration',
  'SAP_COM_0A00': 'SAP Ariba Buying UI Integration',
  'SAP_COM_0574': 'SAP BTP Connectivity Service - On Premise Integration',
  'SAP_COM_0A34': 'SAP Build - Extensibility Integration',
  'SAP_COM_0A61': 'SAP Build Process Automation - Master Data Governance Process Integration',
  'SAP_COM_0743': 'SAP Business Accelerator Hub - Open Resource Discovery Integration',
  'SAP_COM_0A84': 'SAP Business Network - Supplier Search UI Integration',
  'SAP_COM_0042': 'SAP Business Warehouse Integration',
  'SAP_COM_0A20': 'SAP Cash Application for ISLM Integration',
  'SAP_COM_0650': 'SAP Cash Application Integration',
  'SAP_COM_0897': 'SAP Central Invoice Management - UI Integration',
  'SAP_COM_0690': 'SAP Cloud ALM - Change and Deployment Management Integration',
  'SAP_COM_0527': 'SAP Cloud ALM for operations - Application Monitoring Push Integration',
  'SAP_COM_0A43': 'SAP Cloud Application Event Hub - UI Integration',
  'SAP_COM_0892': 'SAP Cloud Application Event Hub Integration',
  'SAP_COM_0200': 'SAP Cloud Connector Integration (Obsolete)',
  'SAP_COM_0838': 'SAP Cloud for Real Estate - UI Integration',
  'SAP_COM_0213': 'SAP Cloud for Real Estate Contract Management Integration',
  'SAP_COM_0066': 'SAP Cloud Identity Access Governance Integration',
  'SAP_COM_0180': 'SAP Cloud Platform - Financials Integration',
  'SAP_COM_0434': 'SAP Cloud Platform ABAP Environment - CRP Usage Integration',
  'SAP_COM_0510': 'SAP Cloud Platform ABAP Environment - Software Component Test Integration',
  'SAP_COM_0235': 'SAP Cloud Platform Business Rules - Inbound Integration',
  'SAP_COM_0236': 'SAP Cloud Platform Business Rules - Outbound Integration',
  'SAP_COM_0528': 'SAP Cloud Platform Master Data for Workforce Integration(obsolete)',
  'SAP_COM_0575': 'SAP Cloud Platform Master Data Service for Workforce Integration (Obsolete)',
  'SAP_COM_0835': 'SAP Collaboration Manager Integration',
  'SAP_COM_0676': 'SAP Conversational AI Integration',
  'SAP_COM_0683': 'SAP CP Notification Service Integration',
  'SAP_COM_0576': 'SAP Data Intelligence - Metadata Explorer Integration',
  'SAP_COM_0531': 'SAP Datasphere - ABAP CDS Extraction - OData Integration (Deprecated)',
  'SAP_COM_0532': 'SAP Datasphere - ABAP CDS Extraction - WebSocket Integration',
  'SAP_COM_0216': 'SAP Digital Payments Add-On Integration',
  'SAP_COM_0653': 'SAP Digital Payments Add-On Integration',
  'SAP_COM_0A67': 'SAP Document AI - UI Integration',
  'SAP_COM_0597': 'SAP Document Management Service - Attachments Integration',
  'SAP_COM_0194': 'SAP Document Management Service - Notification Inbound Integration',
  'SAP_COM_0191': 'SAP Document Management Service - OAuth2.0 mTLS Outbound Integration',
  'SAP_COM_0668': 'SAP Document Management Service - Outbound Integration',
  'SAP_COM_0190': 'SAP Document Management Service - SAML Bearer Outbound Integration',
  'SAP_COM_0A66': 'SAP Dynamic Forms Integration',
  'SAP_COM_0011': 'SAP Enable Now Integration',
  'SAP_COM_0B10': 'SAP FSM - Plant Maintenance - CPI Based Integration',
  'SAP_COM_0B12': 'SAP FSM - Plant Maintenance - Direct Integration (P2P)',
  'SAP_COM_0084': 'SAP Global Trade Services Integration',
  'SAP_COM_0246': 'SAP GR/IR Account Reconciliation Status Proposals Integration (Obsolete)',
  'SAP_COM_0A98': 'SAP Green Ledger - UI Integration',
  'SAP_COM_0573': 'SAP HANA Spatial Services Integration',
  'SAP_COM_0492': 'SAP Integration Suite, Advanced Event Mesh Integration',
  'SAP_COM_0493': 'SAP Integration Suite, Advanced Event Mesh Integration, Validation Service',
  'SAP_COM_0275': 'SAP Localization Hub - eDocuments - DCS Integration',
  'SAP_COM_0047': 'SAP Localization Hub - eDocuments Integration',
  'SAP_COM_0249': 'SAP Localization Hub - External Tax Calculation Engine Integration',
  'SAP_COM_0549': 'SAP Maintenance Assistant Integration',
  'SAP_COM_0841': 'SAP Market Rates Management - UI Integration',
  'SAP_COM_0659': 'SAP Master Data Integration - Outbound Integration',
  'SAP_COM_0060': 'SAP Order Management Integration',
  'SAP_COM_0863': 'SAP Process Automation Integration',
  'SAP_COM_0A63': 'SAP Real Estate - Finance Interface Integration',
  'SAP_COM_0393': 'SAP Real Estate Contract API Integration',
  'SAP_COM_0918': 'SAP Real Estate Master Data Event Integration',
  'SAP_COM_0697': 'SAP Real Estate Master Data Integration',
  'SAP_COM_0657': 'SAP Remittance Advices Integration',
  'SAP_COM_0098': 'SAP S/4 HANA Extensibility Cockpit \u2013 Best Practices Explorer Integration',
  'SAP_COM_0793': 'SAP S/4HANA Cloud for Credit Integration - Data Integration',
  'SAP_COM_0826': 'SAP S/4HANA Cloud for Credit Integration - UI Integration',
  'SAP_COM_0076': 'SAP S/4HANA Finance Cloud for Customer Payments Integration',
  'SAP_COM_0887': 'SAP S/4HANA for Microsoft Teams - Contact Integration',
  'SAP_COM_0A17': 'SAP S/4HANA for Microsoft Teams - Situation Notification Integration',
  'SAP_COM_0A32': 'SAP S/4HANA for Microsoft Teams - Task Notification Integration',
  'SAP_COM_0860': 'SAP S/4HANA for Microsoft Teams - UI Integration',
  'SAP_COM_0930': 'SAP S/4HANA Migration Cockpit - Data Migration to BTP Integration',
  'SAP_COM_0525': 'SAP S/4HANA Procurement Hub - Ariba Central Contract Management Integration',
  'SAP_COM_0292': 'SAP S/4HANA Procurement Hub - Ariba GB - Hub to Ariba GB Integration',
  'SAP_COM_0293': 'SAP S/4HANA Procurement Hub - Ariba GB - Hub to Subsidiary Integration',
  'SAP_COM_0420': 'SAP S/4HANA Procurement Hub - Ariba GB - Subsidiary to Hub Integration',
  'SAP_COM_0243': 'SAP S/4HANA Procurement Hub - Central Contract Management Integration',
  'SAP_COM_0515': 'SAP S/4HANA Procurement Hub - Central Invoice Hub Integration (Obsolete)',
  'SAP_COM_0516': 'SAP S/4HANA Procurement Hub - Central Invoice Satellite Integration',
  'SAP_COM_0266': 'SAP S/4HANA Procurement Hub - Central Purchasing Inbound Integration',
  'SAP_COM_0267': 'SAP S/4HANA Procurement Hub - Central Purchasing Outbound Integration.',
  'SAP_COM_0736': 'SAP S/4HANA Procurement Hub - Central Request For Quotation Integration',
  'SAP_COM_0512': 'SAP S/4HANA Procurement Hub - Central Sourcing Hub Integration',
  'SAP_COM_0513': 'SAP S/4HANA Procurement Hub - Central Sourcing Satellite Integration',
  'SAP_COM_0737': 'SAP S/4HANA Procurement Hub - Central Supplier Quotation Integration',
  'SAP_COM_0673': 'SAP S/4HANA Procurement Hub - Centrally Managed PO with Supplier Integration',
  'SAP_COM_0587': 'SAP S/4HANA Procurement Hub - Foundation Layer Hub Integration',
  'SAP_COM_0586': 'SAP S/4HANA Procurement Hub - Foundation Layer Satellite Integration',
  'SAP_COM_0090': 'SAP S/4HANA Procurement Hub Integration',
  'SAP_COM_0672': 'SAP S/4HANA Procurement Hub-Central Purchase Contract with Supplier Integration',
  'SAP_COM_0564': 'SAP Self-Billing Cockpit Integration',
  'SAP_COM_0642': 'SAP Subscription Billing - API Integration',
  'SAP_COM_0884': 'SAP Subscription Billing - Event Consumption Integration',
  'SAP_COM_0845': 'SAP Subscription Billing - UI Integration',
  'SAP_COM_0095': 'SAP Subscription Billing with Sales Billing Integration',
  'SAP_COM_0686': 'SAP SuccessFactors Employee Central - UI Integration',
  'SAP_COM_0A76': 'SAP Task Center - Task Consumption Integration',
  'SAP_COM_0501': 'SAP Task Center Integration',
  'SAP_COM_0922': 'SAP Treasury Management - Financial Transaction Integration',
  'SAP_COM_0B26': 'SAP Treasury Management - Financial Transaction Integration',
  'SAP_COM_0839': 'SAP Treasury Management - SAP Trading Platform Integration',
  'SAP_COM_0226': 'SAP Treasury Management - SAP Trading Platform Integration (Deprecated)',
  'SAP_COM_0954': 'SAP Treasury Management - Securities Master Data Integration',
  'SAP_COM_0203': 'SAP Treasury Market Rate Integration',
  'SAP_COM_0222': 'SAP Watch List Screening - Screening Hits Integration',
  'SAP_COM_0219': 'SAP Watch List Screening - Screening Integration',
  'SAP_COM_0013': 'SAP Web IDE Integration (Obsolete)',
  'SAP_COM_0637': 'SAP Workflow Management Process Visibility Capability Integration',
  'SAP_COM_0542': 'SAP Workflow Management Workflow Capability Integration',
  'SAP_COM_0750': 'Security Audit Log Integration',
  'SAP_COM_0961': 'Serial Number Management Integration',
  'SAP_COM_0802': 'Service - Field Service Management UI Integration',
  'SAP_COM_0717': 'Service - In-House Repair OData Integration',
  'SAP_COM_0764': 'Service - Master Data Integration',
  'SAP_COM_0933': 'Service - Repair Confirmation Integration',
  'SAP_COM_0858': 'Service - Repair Confirmation SOAP Integration',
  'SAP_COM_0742': 'Service - Repair Order Integration',
  'SAP_COM_0677': 'Service - Repair Order SOAP Integration',
  'SAP_COM_0744': 'Service - Repair Quotation Integration',
  'SAP_COM_0687': 'Service - SAP Field Service Management - Direct Integration (P2P)',
  'SAP_COM_0A50': 'Service - SAP FSM -CPI Based Integration',
  'SAP_COM_0352': 'Service Confirmation OData Integration',
  'SAP_COM_0423': 'Service Confirmation SOAP Integration',
  'SAP_COM_0558': 'Service Contract OData Integration',
  'SAP_COM_0789': 'Service Contract OData V4 Integration',
  'SAP_COM_0436': 'Service Contract SOAP Integration',
  'SAP_COM_0788': 'Service Contract Template Integration',
  'SAP_COM_0A92': 'Service Document Settlement Rules Integration',
  'SAP_COM_0146': 'Service Entry Sheet Integration',
  'SAP_COM_0237': 'Service Entry Sheet Process Integration',
  'SAP_COM_0350': 'Service Order OData Integration',
  'SAP_COM_0424': 'Service Order SOAP Integration',
  'SAP_COM_0715': 'Service Order Template Integration',
  'SAP_COM_0355': 'Service Quotation Integration',
  'SAP_COM_0530': 'Service Quotation Integration',
  'SAP_COM_0831': 'SLT - CDS View Extraction Integration',
  'SAP_COM_0026': 'Social Collaboration Integration',
  'SAP_COM_0582': 'Software Assembly Integration',
  'SAP_COM_0948': 'Software Component Management Integration',
  'SAP_COM_0367': 'Sold-to Party Assignment of Sales Scheduling Agreement Integration',
  'SAP_COM_0445': 'Sourcing and Procurement Scheduling Agreements With Suppliers Integration',
  'SAP_COM_0224': 'Sourcing and Procurement with Suppliers Integration',
  'SAP_COM_0A80': 'Stock Transport Order Integration',
  'SAP_COM_0700': 'SuccessFactors Payment Options Check Integration',
  'SAP_COM_0137': 'Supplier Activity Integration',
  'SAP_COM_0138': 'Supplier Activity Task Integration',
  'SAP_COM_0904': 'Supplier Confirmation Integration',
  'SAP_COM_0827': 'Supplier Confirmation Process Integration',
  'SAP_COM_0828': 'Supplier Confirmation Third-party Integration',
  'SAP_COM_0139': 'Supplier Evaluation Response Integration',
  'SAP_COM_0122': 'Supplier Evaluation Scorecard Integration',
  'SAP_COM_0057': 'Supplier Invoice Integration',
  'SAP_COM_0384': 'Supply Availability Protection Plan Integration',
  'SAP_COM_0347': 'Support User Request Log Read Integration',
  'SAP_COM_0664': 'Sustainability - Product Footprint Management Integration',
  'SAP_COM_0883': 'Sustainability Data Exchange Integration',
  'SAP_COM_0465': 'System for Cross-domain Identity Management Integration',
  'YY1_TASK_CENTER_TEST': 'Task Center Test',
  'SAP_COM_0620': 'Test Automation - Cloud ALM Integration',
  'YY1_TESTCOMMUSER': 'Test for CFO Dashboard',
  'SAP_COM_0253': 'Text Analysis - Purchasing (Deprecated)',
  'SAP_COM_0850': 'Transportation Management - Advanced Shipping Notification Integration',
  'SAP_COM_0756': 'Transportation Management - Freight Agreement Integration',
  'SAP_COM_0906': 'Transportation Management - Freight Booking Integration',
  'SAP_COM_0905': 'Transportation Management - Freight Order Integration',
  'SAP_COM_0908': 'Transportation Management - Freight Unit Integration',
  'SAP_COM_0813': 'Transportation Management - LSP Freight Booking Integration',
  'SAP_COM_0534': 'Transportation Management - LSP Freight Order Integration',
  'SAP_COM_0414': 'Transportation Management - Order-Based Transportation Consolidation Integration',
  'SAP_COM_0767': 'Transportation Management - Rate Table Integration',
  'SAP_COM_0660': 'UI Text Translation Adaptation Integration',
  'SAP_COM_0086': 'UI Theme Designer Integration',
  'SAP_COM_0623': 'UI Theme Designer Integration',
  'SAP_COM_0929': 'Update Source for Project Demands Integration',
  'SAP_COM_0537': 'Variant Configuration and Pricing Integration',
  'SAP_COM_0323': 'Visual Business - GeoJSON Inbound Integration',
  'SAP_COM_0A78': 'WalkMe Digital Adoption Platform - Outbound Integration',
  'SAP_COM_0A65': 'Warehouse Management Control Cycle Integration',
  'SAP_COM_0386': 'Warehousing - Attachment Service Integration',
  'SAP_COM_0875': 'Warehousing - ERP Integration',
  'SAP_COM_0385': 'Warehousing - Inbound Delivery Integration',
  'SAP_COM_0374': 'Warehousing - Master Data Integration',
  'SAP_COM_0378': 'Warehousing - Physical Inventory Integration',
  'SAP_COM_0356': 'Warehousing - Process Outbound Delivery Order Integration',
  'SAP_COM_0353': 'Warehousing - Process Warehouse Task Integration',
  'SAP_COM_0755': 'Warehousing - Stock Integration',
  'SAP_COM_0766': 'Warranty Claim Management Integration',
  'SAP_COM_0632': 'Web Dynpro ABAP ALV for PDF Signing Integration (SAP_COM_0632)',
  'SAP_COM_0914': 'Workforce Availability Integration',
  'SAP_COM_0A35': 'Workforce Person OData Integration',
  'SAP_COM_0027': 'Workforce Timesheet Integration',
  'SAP_COM_0242': 'WSIL Integration',
  'SAP_COM_0184': 'Extended Warehouse Management Integration',
  'SAP_COM_0019': 'Workforce Integration',
  'SAP_COM_0055': 'Finance - Organization Management Integration',
  'SAP_COM_0058': 'Finance - Payment Integration',
  'SAP_COM_0059': 'Finance - Dunning Integration',
  'SAP_COM_0264': 'Service Integration',
  'SAP_COM_0317': 'Quality Management Integration',
};
